=== alokkumarr/my-big-project-/sip-services/sip-proxy-service/src/main/resources/schema/es-search-response-schema.json
{
  "id": "http://synchronoss.com/esResponse.json",
  "type": "object",
  "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#",
  "properties": {
    "took": {
      "id": "/properties/took",
      "type": "integer",
      "title": "The Took Schema",
      "description": "An explanation about the purpose of this instance.",
      "default": 0
      
    },
    "timed_out": {
      "id": "/properties/timed_out",
      "type": "boolean",
      "title": "The Timed_out Schema",
      "description": "An explanation about the purpose of this instance.",
      "default": false
      
    },
    "_shards": {
      "id": "/properties/_shards",
      "type": "object",
      "properties": {
        "total": {
          "id": "/properties/_shards/properties/total",
          "type": "integer",
          "title": "The Total Schema",
          "description": "An explanation about the purpose of this instance.",
          "default": 0
        },
        "successful": {
          "id": "/properties/_shards/properties/successful",
          "type": "integer",
          "title": "The Successful Schema",
          "description": "An explanation about the purpose of this instance.",
          "default": 0
          
        },
        "failed": {
          "id": "/properties/_shards/properties/failed",
          "type": "integer",
          "title": "The Failed Schema",
          "description": "An explanation about the purpose of this instance.",
          "default": 0
        }
      }
    },
    "hits": {
      "id": "/properties/hits",
      "type": "object",
      "properties": {
        "total": {
          "id": "/properties/hits/properties/total",
          "type": "integer",
          "title": "The Total Schema",
          "description": "An explanation about the purpose of this instance.",
          "default": 0
          
        },
        "max_score": {
          "id": "/properties/hits/properties/max_score",
          "type": "number",
          "title": "The Max_score Schema",
          "description": "An explanation about the purpose of this instance.",
          "default": 0
        },
        "hits": {
          "id": "/properties/hits/properties/hits",
          "type": "array"
        }
      }
    },
    "aggregations": {
      "id": "/properties/aggregations",
      "type": "object"
    }
  }
}

=== alokkumarr/my-big-project-/src/main/javascript/app/common/components/charts/mocks/Day.json
{
  "took": 63,
  "timed_out": false,
  "_shards": {
    "total": 2,
    "successful": 2,
    "failed": 0
  },
  "hits": {
    "total": 651072,
    "max_score": 0.0,
    "hits": [
    ]
  },
  "aggregations": {
    "filtered": {
      "doc_count": 649629,
      "split_by": {
        "buckets": [
          {
            "key_as_string": "11-01-2015",
            "key": 1446336000000,
            "doc_count": 6,
            "Total_Order_Count": {
              "value": 6.0
            }
          },
          {
            "key_as_string": "11-02-2015",
            "key": 1446422400000,
            "doc_count": 38,
            "Total_Order_Count": {
              "value": 38.0
            }
          },
          {
            "key_as_string": "11-03-2015",
            "key": 1446508800000,
            "doc_count": 50,
            "Total_Order_Count": {
              "value": 50.0
            }
          },
          {
            "key_as_string": "11-04-2015",
            "key": 1446595200000,
            "doc_count": 66,
            "Total_Order_Count": {
              "value": 66.0
            }
          },
          {
            "key_as_string": "11-05-2015",
            "key": 1446681600000,
            "doc_count": 47,
            "Total_Order_Count": {
              "value": 47.0
            }
          },
          {
            "key_as_string": "11-06-2015",
            "key": 1446768000000,
            "doc_count": 60,
            "Total_Order_Count": {
              "value": 60.0
            }
          },
          {
            "key_as_string": "11-07-2015",
            "key": 1446854400000,
            "doc_count": 38,
            "Total_Order_Count": {
              "value": 38.0
            }
          },
          {
            "key_as_string": "11-08-2015",
            "key": 1446940800000,
            "doc_count": 8,
            "Total_Order_Count": {
              "value": 8.0
            }
          },
          {
            "key_as_string": "11-09-2015",
            "key": 1447027200000,
            "doc_count": 100,
            "Total_Order_Count": {
              "value": 100.0
            }
          },
          {
            "key_as_string": "11-10-2015",
            "key": 1447113600000,
            "doc_count": 78,
            "Total_Order_Count": {
              "value": 78.0
            }
          },
          {
            "key_as_string": "11-11-2015",
            "key": 1447200000000,
            "doc_count": 80,
            "Total_Order_Count": {
              "value": 80.0
            }
          },
          {
            "key_as_string": "11-12-2015",
            "key": 1447286400000,
            "doc_count": 76,
            "Total_Order_Count": {
              "value": 76.0
            }
          },
          {
            "key_as_string": "11-13-2015",
            "key": 1447372800000,
            "doc_count": 78,
            "Total_Order_Count": {
              "value": 78.0
            }
          },
          {
            "key_as_string": "11-14-2015",
            "key": 1447459200000,
            "doc_count": 57,
            "Total_Order_Count": {
              "value": 57.0
            }
          },
          {
            "key_as_string": "11-15-2015",
            "key": 1447545600000,
            "doc_count": 47,
            "Total_Order_Count": {
              "value": 47.0
            }
          },
          {
            "key_as_string": "11-16-2015",
            "key": 1447632000000,
            "doc_count": 137,
            "Total_Order_Count": {
              "value": 137.0
            }
          },
          {
            "key_as_string": "11-17-2015",
            "key": 1447718400000,
            "doc_count": 139,
            "Total_Order_Count": {
              "value": 139.0
            }
          },
          {
            "key_as_string": "11-18-2015",
            "key": 1447804800000,
            "doc_count": 128,
            "Total_Order_Count": {
              "value": 128.0
            }
          },
          {
            "key_as_string": "11-19-2015",
            "key": 1447891200000,
            "doc_count": 157,
            "Total_Order_Count": {
              "value": 157.0
            }
          },
          {
            "key_as_string": "11-20-2015",
            "key": 1447977600000,
            "doc_count": 160,
            "Total_Order_Count": {
              "value": 160.0
            }
          },
          {
            "key_as_string": "11-21-2015",
            "key": 1448064000000,
            "doc_count": 100,
            "Total_Order_Count": {
              "value": 100.0
            }
          },
          {
            "key_as_string": "11-22-2015",
            "key": 1448150400000,
            "doc_count": 87,
            "Total_Order_Count": {
              "value": 87.0
            }
          },
          {
            "key_as_string": "11-23-2015",
            "key": 1448236800000,
            "doc_count": 277,
            "Total_Order_Count": {
              "value": 277.0
            }
          },
          {
            "key_as_string": "11-24-2015",
            "key": 1448323200000,
            "doc_count": 191,
            "Total_Order_Count": {
              "value": 191.0
            }
          },
          {
            "key_as_string": "11-25-2015",
            "key": 1448409600000,
            "doc_count": 203,
            "Total_Order_Count": {
              "value": 203.0
            }
          },
          {
            "key_as_string": "11-26-2015",
            "key": 1448496000000,
            "doc_count": 11,
            "Total_Order_Count": {
              "value": 11.0
            }
          },
          {
            "key_as_string": "11-27-2015",
            "key": 1448582400000,
            "doc_count": 270,
            "Total_Order_Count": {
              "value": 270.0
            }
          },
          {
            "key_as_string": "11-28-2015",
            "key": 1448668800000,
            "doc_count": 182,
            "Total_Order_Count": {
              "value": 182.0
            }
          },
          {
            "key_as_string": "11-29-2015",
            "key": 1448755200000,
            "doc_count": 160,
            "Total_Order_Count": {
              "value": 160.0
            }
          },
          {
            "key_as_string": "11-30-2015",
            "key": 1448841600000,
            "doc_count": 461,
            "Total_Order_Count": {
              "value": 461.0
            }
          },
          {
            "key_as_string": "12-01-2015",
            "key": 1448928000000,
            "doc_count": 459,
            "Total_Order_Count": {
              "value": 459.0
            }
          },
          {
            "key_as_string": "12-02-2015",
            "key": 1449014400000,
            "doc_count": 361,
            "Total_Order_Count": {
              "value": 361.0
            }
          },
          {
            "key_as_string": "12-03-2015",
            "key": 1449100800000,
            "doc_count": 467,
            "Total_Order_Count": {
              "value": 467.0
            }
          },
          {
            "key_as_string": "12-04-2015",
            "key": 1449187200000,
            "doc_count": 465,
            "Total_Order_Count": {
              "value": 465.0
            }
          },
          {
            "key_as_string": "12-05-2015",
            "key": 1449273600000,
            "doc_count": 288,
            "Total_Order_Count": {
              "value": 288.0
            }
          },
          {
            "key_as_string": "12-06-2015",
            "key": 1449360000000,
            "doc_count": 200,
            "Total_Order_Count": {
              "value": 200.0
            }
          },
          {
            "key_as_string": "12-07-2015",
            "key": 1449446400000,
            "doc_count": 609,
            "Total_Order_Count": {
              "value": 609.0
            }
          },
          {
            "key_as_string": "12-08-2015",
            "key": 1449532800000,
            "doc_count": 539,
            "Total_Order_Count": {
              "value": 539.0
            }
          },
          {
            "key_as_string": "12-09-2015",
            "key": 1449619200000,
            "doc_count": 557,
            "Total_Order_Count": {
              "value": 557.0
            }
          },
          {
            "key_as_string": "12-10-2015",
            "key": 1449705600000,
            "doc_count": 538,
            "Total_Order_Count": {
              "value": 538.0
            }
          },
          {
            "key_as_string": "12-11-2015",
            "key": 1449792000000,
            "doc_count": 539,
            "Total_Order_Count": {
              "value": 539.0
            }
          },
          {
            "key_as_string": "12-12-2015",
            "key": 1449878400000,
            "doc_count": 327,
            "Total_Order_Count": {
              "value": 327.0
            }
          },
          {
            "key_as_string": "12-13-2015",
            "key": 1449964800000,
            "doc_count": 158,
            "Total_Order_Count": {
              "value": 158.0
            }
          },
          {
            "key_as_string": "12-14-2015",
            "key": 1450051200000,
            "doc_count": 637,
            "Total_Order_Count": {
              "value": 637.0
            }
          },
          {
            "key_as_string": "12-15-2015",
            "key": 1450137600000,
            "doc_count": 796,
            "Total_Order_Count": {
              "value": 796.0
            }
          },
          {
            "key_as_string": "12-16-2015",
            "key": 1450224000000,
            "doc_count": 787,
            "Total_Order_Count": {
              "value": 787.0
            }
          },
          {
            "key_as_string": "12-17-2015",
